const { validationResult } = require("express-validator");

/**
 * Reusable middleware that checks for validation errors generated by express-validator
 * and returns a structured 400 response if any errors exist.
 */
const validate = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ success: false, errors: errors.array() });
  }
  next();
};

module.exports = validate;
